// <auto-generated />
using System;
using FST.TournamentPlanner.DB.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FST.TournamentPlanner.DB.Migrations
{
    [DbContext(typeof(PlannerContext))]
    [Migration("20190411160505_AddName2")]
    partial class AddName2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FST.TournamentPlanner.DB.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Title");

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ItemTest","test");
                });

            modelBuilder.Entity("FST.TournamentPlanner.DB.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Name");

                    b.Property<string>("Name2");

                    b.HasKey("Id");

                    b.ToTable("UserTest","test");
                });

            modelBuilder.Entity("FST.TournamentPlanner.DB.Models.Item", b =>
                {
                    b.HasOne("FST.TournamentPlanner.DB.Models.User")
                        .WithMany("Items")
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
