// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace FST.TournamentPlanner.UI.Model.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Class representing a play area
    /// </summary>
    public partial class PlayArea
    {
        /// <summary>
        /// Initializes a new instance of the PlayArea class.
        /// </summary>
        public PlayArea() { }

        /// <summary>
        /// Initializes a new instance of the PlayArea class.
        /// </summary>
        public PlayArea(int? id = default(int?), string name = default(string), string description = default(string))
        {
            Id = id;
            Name = name;
            Description = description;
        }

        /// <summary>
        /// Id of the play area
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// Name of the play area
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Description of the play area
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

    }
}
